/** Client-safe Agent Teams request, result, and view vocabulary. */

export type {
  CreateTeamTaskRequest,
  GuideTeamMemberRemoteRequest,
  SendTeamMessageRequest,
  SendTeamMessageResult,
  SpawnTeamMemberRemoteRequest,
  SpawnTeammateRequest,
  SpawnTeammateResult,
  StartTeamDebateRequest,
  TeamDebateAction,
  TeamDebateId,
  TeamDebatePhase,
  TeamDebateSnapshot,
  TeamDebateStatus,
  TeamDebateTransition,
  TeamMemberSnapshot,
  TeamMemberView,
  TeamMessageId,
  TeamMessageSnapshot,
  TeamMessageSource,
  TeamProjection,
  TeamTaskAction,
  TeamTaskId,
  TeamTaskMutationResult,
  TeamTaskSnapshot,
  TeamTaskStatus,
  TeamTaskView,
  TeamView,
  TeamWaitResult,
  UpdateTeamDebateRequest,
  UpdateTeamTaskRequest,
} from './types.ts'
